# Generated by Django 3.2.5 on 2021-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbrank',
            field=models.CharField(default=True, max_length=2, verbose_name='Imdb Puanı'),
        ),
    ]
