# Generated by Django 3.2.5 on 2021-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdbrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbrank',
            field=models.CharField(default=True, max_length=3, verbose_name='Imdb Puanı'),
        ),
    ]
